name: CI - Pull Request

on:
  pull_request:

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || github.sha }}
  cancel-in-progress: true

permissions: {}

env:
  FORCE_COLOR: true
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  preview-pr:
    name: Continuous Deployment Snapshot
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/preview.yml@e8ab1d958f7a32e610f9d96fe36eedd8ee6a0d73 # main
    with:
      build-cmd: "pnpm ci:build"
