name: CI - Push to Main

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

env:
  FORCE_COLOR: true
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  release:
    name: Release
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/release.yml@e8ab1d958f7a32e610f9d96fe36eedd8ee6a0d73 # main
    with:
      build-cmd: "pnpm ci:build"
      changeset-version: "pnpm ci:version"
      RoleMentionId: "1309310416362537020"

  # mergebot:
  #   name: CI - Merge Bot
  #   if: github.repository_owner == 'withstudiocms' && github.event.head_commit.message != '[ci] lint'
  #   uses: withstudiocms/automations/.github/workflows/mergebot.yml@e8ab1d958f7a32e610f9d96fe36eedd8ee6a0d73 # main
  #   secrets:
  #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_MERGEBOT }}

  preview-main:
    name: Continuous Deployment Snapshot
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
    secrets: inherit
    uses: withstudiocms/automations/.github/workflows/preview.yml@e8ab1d958f7a32e610f9d96fe36eedd8ee6a0d73 # main
    with:
      build-cmd: "pnpm ci:build"
